// Mocks generated by Mockito 5.4.4 from annotations
// in my_quran/test/alquran/data/quran_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_quran/common/common.dart' as _i2;
import 'package:my_quran/features/features.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseResponse_0<T> extends _i1.SmartFake
    implements _i2.BaseResponse<T> {
  _FakeBaseResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuranRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuranRemoteDataSource extends _i1.Mock
    implements _i3.QuranRemoteDataSource {
  @override
  _i4.Future<_i2.BaseResponse<List<_i3.Surah>?>> getSurahs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSurahs,
          [],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<List<_i3.Surah>?>>.value(
            _FakeBaseResponse_0<List<_i3.Surah>?>(
          this,
          Invocation.method(
            #getSurahs,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<List<_i3.Surah>?>>.value(
                _FakeBaseResponse_0<List<_i3.Surah>?>(
          this,
          Invocation.method(
            #getSurahs,
            [],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<List<_i3.Surah>?>>);

  @override
  _i4.Future<_i2.BaseResponse<_i3.Surah?>> getSurah(int? surahNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSurah,
          [surahNumber],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<_i3.Surah?>>.value(
            _FakeBaseResponse_0<_i3.Surah?>(
          this,
          Invocation.method(
            #getSurah,
            [surahNumber],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<_i3.Surah?>>.value(
                _FakeBaseResponse_0<_i3.Surah?>(
          this,
          Invocation.method(
            #getSurah,
            [surahNumber],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i3.Surah?>>);

  @override
  _i4.Future<_i2.BaseResponse<List<_i3.Juz>?>> getJuzs() => (super.noSuchMethod(
        Invocation.method(
          #getJuzs,
          [],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<List<_i3.Juz>?>>.value(
            _FakeBaseResponse_0<List<_i3.Juz>?>(
          this,
          Invocation.method(
            #getJuzs,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<List<_i3.Juz>?>>.value(
                _FakeBaseResponse_0<List<_i3.Juz>?>(
          this,
          Invocation.method(
            #getJuzs,
            [],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<List<_i3.Juz>?>>);

  @override
  _i4.Future<_i2.BaseResponse<_i3.Juz?>> getJuz(int? juzNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJuz,
          [juzNumber],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<_i3.Juz?>>.value(
            _FakeBaseResponse_0<_i3.Juz?>(
          this,
          Invocation.method(
            #getJuz,
            [juzNumber],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.BaseResponse<_i3.Juz?>>.value(
            _FakeBaseResponse_0<_i3.Juz?>(
          this,
          Invocation.method(
            #getJuz,
            [juzNumber],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i3.Juz?>>);

  @override
  _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>> getAyahs(
          _i3.AyahPagination? pagination) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAyahs,
          [pagination],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>>.value(
            _FakeBaseResponse_0<List<_i3.Ayah>?>(
          this,
          Invocation.method(
            #getAyahs,
            [pagination],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>>.value(
                _FakeBaseResponse_0<List<_i3.Ayah>?>(
          this,
          Invocation.method(
            #getAyahs,
            [pagination],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>>);

  @override
  _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>> getAyahsJuz(int? juzNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAyahsJuz,
          [juzNumber],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>>.value(
            _FakeBaseResponse_0<List<_i3.Ayah>?>(
          this,
          Invocation.method(
            #getAyahsJuz,
            [juzNumber],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>>.value(
                _FakeBaseResponse_0<List<_i3.Ayah>?>(
          this,
          Invocation.method(
            #getAyahsJuz,
            [juzNumber],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>>);

  @override
  _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>> getAyahsThroughout(
          _i3.AyahsThroughoutPagination? ayahsThroughout) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAyahsThroughout,
          [ayahsThroughout],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>>.value(
            _FakeBaseResponse_0<List<_i3.Ayah>?>(
          this,
          Invocation.method(
            #getAyahsThroughout,
            [ayahsThroughout],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>>.value(
                _FakeBaseResponse_0<List<_i3.Ayah>?>(
          this,
          Invocation.method(
            #getAyahsThroughout,
            [ayahsThroughout],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>>);

  @override
  _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>> getFullAyahs(
          _i3.AyahsThroughoutPagination? ayahsThroughout) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFullAyahs,
          [ayahsThroughout],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>>.value(
            _FakeBaseResponse_0<List<_i3.Ayah>?>(
          this,
          Invocation.method(
            #getFullAyahs,
            [ayahsThroughout],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>>.value(
                _FakeBaseResponse_0<List<_i3.Ayah>?>(
          this,
          Invocation.method(
            #getFullAyahs,
            [ayahsThroughout],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<List<_i3.Ayah>?>>);
}
