// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:my_quran/features/alquran/data/models/ayah.dart';
import 'package:my_quran/features/alquran/data/models/juz.dart';
import 'package:my_quran/features/alquran/data/models/surah.dart';
import 'package:my_quran/features/bookmark/data/models/bookmark_category.dart';
import 'package:my_quran/features/bookmark/data/models/bookmark_data.dart';
import 'package:my_quran/features/bookmark/data/models/bookmark_type.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AyahAdapter());
    registerAdapter(BookmarkCategoryAdapter());
    registerAdapter(BookmarkDataAdapter());
    registerAdapter(BookmarkTypeAdapter());
    registerAdapter(JuzAdapter());
    registerAdapter(SurahAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AyahAdapter());
    registerAdapter(BookmarkCategoryAdapter());
    registerAdapter(BookmarkDataAdapter());
    registerAdapter(BookmarkTypeAdapter());
    registerAdapter(JuzAdapter());
    registerAdapter(SurahAdapter());
  }
}
