import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive_ce/hive.dart';

import '../../../../lib.dart';

part 'bookmark_category.freezed.dart';
part 'bookmark_category.g.dart';

@customFreezed
@HiveType(typeId: 3, adapterName: "IgnoreBookmarkCategory") // Assign a unique typeId for Hive
abstract class BookmarkCategory with _$BookmarkCategory {
  const BookmarkCategory._();
  
  @customJsonSerializable
  const factory BookmarkCategory({@HiveField(0) String? name, @HiveField(1) String? id}) =
      _BookmarkCategory;

  // Removed Isar-specific code
  // Id get isarId => Isar.autoIncrement;

  // Custom fromJson method generated by Freezed
  factory BookmarkCategory.fromJson(Map<String, dynamic> json) => _$BookmarkCategoryFromJson(json);

}
