import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive_ce/hive.dart';

part 'bookmark_category.freezed.dart';
part 'bookmark_category.g.dart';

@Freezed(fromJson: false, toJson: false)
@HiveType(typeId: 3) // Assign a unique typeId for Hive
@JsonSerializable(fieldRename: FieldRename.snake)
class BookmarkCategory with _$BookmarkCategory {
  const BookmarkCategory._();

  const factory BookmarkCategory({@HiveField(0) String? name, @HiveField(1) String? id}) =
      _BookmarkCategory;

  // Removed Isar-specific code
  // Id get isarId => Isar.autoIncrement;

  // Custom fromJson method generated by Freezed
  factory BookmarkCategory.fromJson(Map<String, dynamic> json) => _$BookmarkCategoryFromJson(json);

  // Custom toJson method generated by Freezed
  Map<String, dynamic> toJson() => _$BookmarkCategoryToJson(this);
}
