import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive_ce/hive.dart';

import '../../../../lib.dart';

part 'bookmark_data.freezed.dart';
part 'bookmark_data.g.dart';

@customFreezed
@HiveType(typeId: 4) // Assign a unique typeId for Hive
abstract class BookmarkData with _$BookmarkData {
  const BookmarkData._();

  @customJsonSerializable
  const factory BookmarkData({
    @HiveField(0) String? title,
    @HiveField(1) String? subtitle,
    @HiveField(2) int? dataId,
    @HiveField(3) String? categoryId,
    @HiveField(4) String? type,
    @HiveField(5) String? id,
  }) = _BookmarkData;

  // Custom fromJson method generated by Freezed
  factory BookmarkData.fromJson(Map<String, dynamic> json) => _$BookmarkDataFromJson(json);

}
