name: Dart

on:
  push:
    branches: [ "feature/build-prod" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .fvm
          key: flutter-${{ runner.os }}-flutter-3.24.0
          restore-keys: |
            flutter-${{ runner.os }}-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
          
      - run: flutter --version
        
      - name: Install FVM
        run: dart pub global activate fvm

      - name: Use Flutter version with FVM
        run: yes | fvm use 3.24.0

      - name: Set Flutter to use FVM in this project
        run: fvm flutter --version

      - name: pub get
        run: fvm flutter pub get

      - name: Analyze project source
        run: fvm flutter analyze

      - name: Run tests
        run: fvm flutter test
