name: Dart

on:
  push:
    branches: [ "feature/build-prod" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Cache FVM Flutter SDK
        id: fvm-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .fvm/versions/3.24.0
          key: fvm-flutter-${{ runner.os }}-3.24.0

      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install FVM
        run: dart pub global activate fvm

      - name: Use Flutter version with FVM
        run: fvm use 3.24.0

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            .dart_tool
            .packages
            pubspec.lock
            .fvm/flutter_sdk/.pub-cache
          key: fvm-flutter-dependencies-${{ runner.os }}-${{ hashFiles('pubspec.yaml') }}

      - name: Install Flutter dependencies
        run: fvm flutter pub get

      - name: Analyze project source
        run: fvm flutter analyze

      # - name: Run tests
      #   run: fvm flutter test
